# Generated by Django 5.1.2 on 2024-11-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('graduation_year', models.IntegerField()),
                ('degree', models.CharField(max_length=100)),
                ('current_company', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='alumni_images/')),
            ],
            options={
                'verbose_name_plural': 'Alumni',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='faculty_images/')),
            ],
            options={
                'verbose_name_plural': 'Faculty Members',
            },
        ),
    ]
